### ISSUE TITLE
Counter Example Won't Run on Chrome

### ISSUE THREAD

**Issue by dleuck** [swiftwasm/swiftwasm-pad#17]
https://pad.swiftwasm.org/ isn't working on Chrome. If you click "Run" with the default example it throws a DOMException:

Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': ArrayBuffer is not detachable and could not be cloned.
    at writeOutput (https://pad.swiftwasm.org/main.worker.js:1:188854)
    at https://pad.swiftwasm.org/SwiftWasmPad.wasm:wasm-function[3372]:0xa25fe
    at https://pad.swiftwasm.org/SwiftWasmPad.wasm:wasm-function[27]:0xf44a
    at t.start (https://pad.swiftwasm.org/main.worker.js:1:47953)
    at https://pad.swiftwasm.org/main.worker.js:1:189018

**Comment by kateinoigakukun** [comment]
Thank you for your report. It has been fixed now by https://github.com/swiftwasm/swiftwasm-pad/commit/7cf0f0a3b8b9749e38cafda68b688c650f77ce91.
