### ISSUE TITLE
Make it available on a custom domain

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/swiftwasm-pad#3]
I would like to make this available on pad.swiftwasm.org. Would we need to set this up on Netlify, or re-deploy to GitHub Pages? @kateinoigakukun please let me know what do you think would be the best way to approach this.

**Comment by kateinoigakukun** [comment]
I'm not sure how fast GitHub Pages can deliver large content, so I used Netlify. But it's worth to compare both of them.

**Comment by kateinoigakukun** [comment]
In my environment, https://kateinoigakukun.github.io/swiftwasm-pad/index.html is faster than https://swiftwasm-pad.netlify.app/ 😮 
@MaxDesiatov Which version is faster in your environment?

**Comment by MaxDesiatov** [comment]
Yes, Netlify is slower for me too. It's 3-4 seconds on average vs 1-1.5 seconds on GitHub Pages.

**Comment by kateinoigakukun** [comment]
OK, I've added CNAME file. After [this job](https://github.com/kateinoigakukun/swiftwasm-pad/actions/runs/321655341) will be finished, it will be ready for setting DNS record.

In addition, what do you think about moving this repo into swiftwasm org?

**Comment by MaxDesiatov** [comment]
Transferring it to the SwiftWasm org makes sense to me if you don't mind 👍

**Comment by kateinoigakukun** [comment]
deployed

**Comment by MaxDesiatov** [comment]
It works! https://pad.swiftwasm.org/
You may need to wait up to an hour if you see SSL cert errors, it's still being propagated through CDNs.

**Comment by MaxDesiatov** [comment]
Would you be able to set up a redirect from https://swiftwasm-pad.netlify.app/?

**Comment by MaxDesiatov** [comment]
I'll reopen the issue until that redirect from Netlify is working if you don't mind.

**Comment by kateinoigakukun** [comment]
I've set redirect setting 👍

**Comment by MaxDesiatov** [comment]
Lovely, thanks!
